services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER_NAME}
    ports:
      - '15432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
